// <auto-generated />
namespace CadastroDeClientes.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migrations_Banco_Inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrations_Banco_Inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171941558_Migrations_Banco_Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
